### ISSUE TITLE
Incorrect ArcGIS JSON ?

### ISSUE THREAD

**Issue by baerbock** [gavinr/arcgis-json-to-geojson#24]
Dear Gavin,

what's non-standard with the ArcGIS JSON at https://www.arcgis.com/sharing/rest/content/items/2444834968bf4cf99844c63ca6e3dcfa/data?f=geojson

I'm just very curious.

**Comment by gavinr** [comment]
@baerbock that item is a [web map](https://doc.arcgis.com/en/arcgis-online/reference/what-is-web-map.htm), and the layers in that web map are all [Feature Collections](https://enterprise.arcgis.com/en/portal/latest/use/feature-layers.htm#GUID-304463C0-25BD-4FEA-8DD6-AD82F2C96B56) instead of [Hosted Feature Layers](https://enterprise.arcgis.com/en/portal/latest/use/feature-layers.htm#ESRI_SECTION1_FD2040756D7E43E6A06AE0CE7CC2595E). This project is only designed to take Esri JSON from Hosted Feature Service queries. It is not designed to translate a web map with Feature Collections. 

If you need more help translating your files, I would suggest asking your question on https://community.esri.com/community/gis/web-gis/arcgisonline
